/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Paper__factory } from "./Paper__factory";
export { PaperFactory__factory } from "./PaperFactory__factory";
