/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PaperFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createPaper"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PaperCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createPaper",
    values: [AddressLike[], string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPaper",
    data: BytesLike
  ): Result;
}

export namespace PaperCreatedEvent {
  export type InputTuple = [paper: AddressLike, owner: AddressLike];
  export type OutputTuple = [paper: string, owner: string];
  export interface OutputObject {
    paper: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaperFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PaperFactory;
  waitForDeployment(): Promise<this>;

  interface: PaperFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPaper: TypedContractMethod<
    [
      _references: AddressLike[],
      _initialuri: string,
      _baseFundingPrice: BigNumberish,
      _referenceRoyalty: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPaper"
  ): TypedContractMethod<
    [
      _references: AddressLike[],
      _initialuri: string,
      _baseFundingPrice: BigNumberish,
      _referenceRoyalty: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PaperCreated"
  ): TypedContractEvent<
    PaperCreatedEvent.InputTuple,
    PaperCreatedEvent.OutputTuple,
    PaperCreatedEvent.OutputObject
  >;

  filters: {
    "PaperCreated(address,address)": TypedContractEvent<
      PaperCreatedEvent.InputTuple,
      PaperCreatedEvent.OutputTuple,
      PaperCreatedEvent.OutputObject
    >;
    PaperCreated: TypedContractEvent<
      PaperCreatedEvent.InputTuple,
      PaperCreatedEvent.OutputTuple,
      PaperCreatedEvent.OutputObject
    >;
  };
}
